### ISSUE TITLE
SIGSEGV on v0.38.1

### ISSUE THREAD

**Issue by dragon3** [k1LoW/octocov#146]
I got the following error on `v0.38.1` via `octocov-action@v0.38.1`.
Do you have any idea about the SIGSEGV?

I confirmed that `v0.38.0` doesn't have this issue. ( So now I'm using it for now )

I've tried to use `v0.38.1` binary directly, but got the same error.

```
octocov version 0.38.1

                       #XXXX (xxxxxxx)  
----------------------------------------
  Coverage                       xx.x%  
  Code to Test Ratio             x:x.x  
  Test Execution Time            XmXXs  

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f5988e39360]

runtime stack:
runtime.throw({0x164bc18, 0x7f5988b4b653})
	/Users/k1low/sdk/go1.17.7/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/Users/k1low/sdk/go1.17.7/src/runtime/signal_unix.go:719 +0x396

goroutine 41 [syscall]:
runtime.cgocall(0x10f1310, 0xc00006a590)
	/Users/k1low/sdk/go1.17.7/src/runtime/cgocall.go:156 +0x5c fp=0xc00006a568 sp=0xc00006a530 pc=0x40527c
net._C2func_getaddrinfo(0xc001349c60, 0x0, 0xc00134daa0, 0xc002476480)
	_cgo_gotypes.go:91 +0x56 fp=0xc00006a590 sp=0xc00006a568 pc=0x68b116
net.cgoLookupIPCNAME.func1({0xc001349c60, 0xc00006a738, 0x4479af}, 0x16023b9, 0x3)
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:163 +0x9f fp=0xc00006a5e8 sp=0xc00006a590 pc=0x68ce5f
net.cgoLookupIPCNAME({0x14e22c8, 0x2}, {0x16023b9, 0xc00006a77c})
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:163 +0x16d fp=0xc00006a738 sp=0xc00006a5e8 pc=0x68c6ad
net.cgoIPLookup(0x0, {0x14e22c8, 0x0}, {0x16023b9, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:220 +0x3b fp=0xc00006a7a8 sp=0xc00006a738 pc=0x68cf1b
net.cgoLookupIP·dwrap·25()
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:230 +0x36 fp=0xc00006a7e0 sp=0xc00006a7a8 pc=0x68d396
runtime.goexit()
	/Users/k1low/sdk/go1.17.7/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00006a7e8 sp=0xc00006a7e0 pc=0x4655e1
created by net.cgoLookupIP
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:230 +0x125

goroutine 1 [chan receive]:
cloud.google.com/go/compute/metadata.testOnGCE()
	/Users/k1low/go/pkg/mod/cloud.google.com/go/compute@v1.0.0/metadata/metadata.go:153 +0x185
cloud.google.com/go/compute/metadata.initOnGCE()
	/Users/k1low/go/pkg/mod/cloud.google.com/go/compute@v1.0.0/metadata/metadata.go:114 +0x17
sync.(*Once).doSlow(0x1aa4340, 0xc0029bd530)
	/Users/k1low/sdk/go1.17.7/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001b61580, {0xc00289c000, 0xdfa, 0xdfa})
	/Users/k1low/sdk/go1.17.7/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc001b61580, {0xc00289c000, 0xc00289c005, 0x56b})
	/Users/k1low/sdk/go1.17.7/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00056e000, {0xc00289c000, 0x6, 0xc0013ed7f8})
	/Users/k1low/sdk/go1.17.7/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0028ee090, {0xc00289c000, 0x0, 0x40b90d})
	/Users/k1low/sdk/go1.17.7/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0013de978, {0x1aa0b20, 0xc0028ee090})
	/Users/k1low/sdk/go1.17.7/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0013de700, {0x1aa44c0, 0xc00056e000}, 0x400)
	/Users/k1low/sdk/go1.17.7/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0013de700, 0x0)
	/Users/k1low/sdk/go1.17.7/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/Users/k1low/sdk/go1.17.7/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0013de700, {0xc00289d000, 0x1000, 0x1})
	/Users/k1low/sdk/go1.17.7/src/crypto/tls/conn.go:1277 +0x16f
net/http.(*persistConn).Read(0xc0001c3200, {0xc00289d000, 0xc002030060, 0xc0013edd30})
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc001335b60)
	/Users/k1low/sdk/go1.17.7/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc001335b60, 0x1)
	/Users/k1low/sdk/go1.17.7/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc0001c3200)
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1747 +0x1e05

goroutine 40 [select]:
net/http.(*persistConn).writeLoop(0xc0001c3200)
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1748 +0x1e65

goroutine 23 [select]:
net/http.(*Transport).getConn(0x2a639a0, 0xc00055e140, {{}, 0x0, {0x15f111b, 0x4}, {0xc000046120, 0x12}, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0x2a639a0, 0xc001b00200)
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0013eeb30, 0x1aa4560)
	/Users/k1low/sdk/go1.17.7/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc001b00200, {0x1aa4560, 0x2a639a0}, {0x14af480, 0x7f599243ef01, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0x289eb20, 0xc001b00200, {0x0, 0xec8e24, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0x289eb20, 0xc001b00200)
	/Users/k1low/sdk/go1.17.7/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/Users/k1low/sdk/go1.17.7/src/net/http/client.go:593
cloud.google.com/go/compute/metadata.testOnGCE.func1()
	/Users/k1low/go/pkg/mod/cloud.google.com/go/compute@v1.0.0/metadata/metadata.go:133 +0x310
created by cloud.google.com/go/compute/metadata.testOnGCE
	/Users/k1low/go/pkg/mod/cloud.google.com/go/compute@v1.0.0/metadata/metadata.go:130 +0xf5

goroutine 24 [select]:
net.cgoLookupIP({0x1ac2848, 0xc0023c5540}, {0x14e22c8, 0x0}, {0x16023b9, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:231 +0x1b7
net.cgoLookupHost({0x1ac2848, 0xc0023c5540}, {0x16023b9, 0x18})
	/Users/k1low/sdk/go1.17.7/src/net/cgo_unix.go:59 +0x55
net.(*Resolver).lookupHost(0x2a621e0, {0x1ac2848, 0xc0023c5540}, {0x16023b9, 0x18})
	/Users/k1low/sdk/go1.17.7/src/net/lookup_unix.go:82 +0xa8
net.(*Resolver).LookupHost(0x0, {0x1ac2848, 0xc0023c5540}, {0x16023b9, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/lookup.go:187 +0x165
cloud.google.com/go/compute/metadata.testOnGCE.func2()
	/Users/k1low/go/pkg/mod/cloud.google.com/go/compute@v1.0.0/metadata/metadata.go:143 +0x45
created by cloud.google.com/go/compute/metadata.testOnGCE
	/Users/k1low/go/pkg/mod/cloud.google.com/go/compute@v1.0.0/metadata/metadata.go:142 +0x15d

goroutine 13 [runnable]:
net.setDefaultSockopts(0x8, 0x2, 0x1, 0x0)
	/Users/k1low/sdk/go1.17.7/src/net/sockopt_linux.go:12 +0x14f
net.socket({0x1ac28b8, 0xc0013822a0}, {0x14e7c69, 0x3}, 0x2, 0x1, 0x0, 0x18, {0x1acadf8, 0x0}, ...)
	/Users/k1low/sdk/go1.17.7/src/net/sock_posix.go:24 +0x99
net.internetSocket({0x1ac28b8, 0xc0013822a0}, {0x14e7c69, 0x3}, {0x1acadf8, 0x0}, {0x1acadf8, 0xc00287c150}, 0xc00138a000, 0x0, ...)
	/Users/k1low/sdk/go1.17.7/src/net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc001b60000, {0x1ac28b8, 0xc0013822a0}, 0x0, 0x12fa6e0)
	/Users/k1low/sdk/go1.17.7/src/net/tcpsock_posix.go:66 +0xa5
net.(*sysDialer).dialTCP(0xc0013822a0, {0x1ac28b8, 0xc0013822a0}, 0x4bd566, 0x2000)
	/Users/k1low/sdk/go1.17.7/src/net/tcpsock_posix.go:62 +0x59
net.(*sysDialer).dialSingle(0xc001b60000, {0x1ac28b8, 0xc0013822a0}, {0x1ab6478, 0xc00287c150})
	/Users/k1low/sdk/go1.17.7/src/net/dial.go:583 +0x28b
net.(*sysDialer).dialSerial(0xc001b60000, {0x1ac28b8, 0xc0013822a0}, {0xc00287a090, 0x1, 0x14ede87})
	/Users/k1low/sdk/go1.17.7/src/net/dial.go:551 +0x312
net.(*Dialer).DialContext(0xc00127c9c0, {0x1ac2880, 0xc0001aa000}, {0x14e7c69, 0x7f59897e7f20}, {0xc000046120, 0x118})
	/Users/k1low/sdk/go1.17.7/src/net/dial.go:428 +0x736
net.(*Dialer).Dial(...)
	/Users/k1low/sdk/go1.17.7/src/net/dial.go:351
net/http.(*Transport).dial(0xc00287e000, {0x1ac2848, 0xc0023c5540}, {0x14e7c69, 0x3000106}, {0xc000046120, 0xffffffffffffffff})
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1169 +0x5a
net/http.(*Transport).dialConn(0x2a639a0, {0x1ac2848, 0xc0023c5540}, {{}, 0x0, {0x15f111b, 0x4}, {0xc000046120, 0x12}, 0x0})
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x0, 0xc001380000)
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/Users/k1low/sdk/go1.17.7/src/net/http/transport.go:1415 +0x3d7
```

**Comment by k1LoW** [comment]
@dragon3 Thank you for your report.

Probably because my build environment has changed.

I'll check and fix that right away.

**Comment by k1LoW** [comment]
ref: https://github.com/k1LoW/octocov/compare/v0.38.0...v0.38.1

**Comment by k1LoW** [comment]
Hi @dragon3 .

I'm afraid I can't reproduce the error you're seeing.

I am trying to rethink the build environment, but I have not been able to reproduce the SEGV, so I am not sure if it has been resolved.

If possible could you give me some more information?

For example, information on the runner running octocov-action would be greatly appreciated! ( it may be hard to... )

## Environment in which reproduction was tried
https://github.com/k1LoW/octocov/blob/86b11532cfee0da9ce0f009a7fe2143756a57b83/.octocov.yml#L9-L11
https://github.com/k1LoW/octocov/actions/runs/1987493391/workflow

**Comment by dragon3** [comment]
@k1LoW 
Thank you for working on it 🙇 

I tried the rebuilt version `octocov-v0.38.1-rebuild.zip` and it worked without any errors 😄 

```
octocov version 0.38.1-next
                       #XXXX (xxxxxxx)  
----------------------------------------
  Coverage                       xx.x%  
  Code to Test Ratio             x:x.x  
  Test Execution Time            XmXXs  
Commenting report...
Skip storing the report: the condition in the `if` section is not met (env.GITHUB_REF == 'refs/heads/main')
Skip pushing generate files: push: is not set
```

---

Here is the information about our environment where octocov-action is running:

- Self-Hosted runner
    - Runner version: `2.288.1`
    - OS version (uname -a): `Linux XXX 5.13.0-1019-gcp #23~20.04.1-Ubuntu SMP Mon Mar 7 13:39:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Let me know if you need any other specific information.

**Comment by k1LoW** [comment]
As a quick fix, I released a rebuilt version.

https://github.com/k1LoW/octocov-action/releases/tag/v0.38.2

I'll think again about the build environment.

**Comment by dragon3** [comment]
Thanks!
I'll try the new version `v0.38.2` and let you know.

**Comment by dragon3** [comment]
I confirmed the `v0.38.2` works 👍 

```
octocov version 0.38.2

                       #XXXX (xxxxxxx)  
----------------------------------------
  Coverage                       xx.x%  
  Code to Test Ratio             x:x.x  
  Test Execution Time            XmXXs  

Commenting report...
Skip storing the report: the condition in the `if` section is not met (env.GITHUB_REF == 'refs/heads/main')
Skip pushing generate files: push: is not set
```
