### ISSUE TITLE
octocov-action with v0.41.0 fails

### ISSUE THREAD

**Issue by toshi0607** [k1LoW/octocov#164]
Thank you for the very useful tool! Our org stated to use this in many projects.

I found the CI stared to fail as soon as the new version released with the same CI and the same test code. I hope the following stack trace will help. I also investigate the cause.

## Before

```console
octocov version 0.40.1

                       feature/xxx-branch
                                  (xxxxxxxx)              
---------------------------------------------------------
  Coverage                                        32.7%  
  Code to Test Ratio                              1:0.5  
  Test Execution Time                             1m22s  

Commenting report...
Skip storing the report: the condition in the `if` section is not met (is_default_branch)
Skip pushing generate files: push: is not set
```

## After

```console
octocov version 0.41.0

                       feature/xxx-branch
                                  (xxxxxxxx)              
---------------------------------------------------------
  Coverage                                        32.7%  
  Code to Test Ratio                              1:0.5  
  Test Execution Time                             1m36s  

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f5cac004360]

runtime stack:
runtime.throw({0x17bde[16](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:17)?, 0x7f5ca4b94623?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/signal_unix.go:802 +0x389

goroutine 52 [syscall]:
runtime.cgocall(0x120bb10, 0xc000c6ed98)
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/cgocall.go:157 +0x5c fp=0xc000c6ed70 sp=0xc000c6ed38 pc=0x40571c
net._C2func_getaddrinfo(0xc0021555d0, 0x0, 0xc0020f8d80, 0xc000010900)
	_cgo_gotypes.go:94 +0x56 fp=0xc000c6ed98 sp=0xc000c6ed70 pc=0x6b2c36
net.cgoLookupIPCNAME.func1({0xc0021555d0, 0x689af2?, 0xc000188980?}, 0xc0018d7c50?, 0x6b919b?)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/cgo_unix.go:160 +0x9f fp=0xc000c6edf0 sp=0xc000c6ed98 pc=0x6b495f
net.cgoLookupIPCNAME({0x16497a4, 0x3}, {0xc0018d7c50, 0xe})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/cgo_unix.go:160 +0x16d fp=0xc000c6ef38 sp=0xc000c6edf0 pc=0x6b41cd
net.cgoIPLookup(0x2d09230?, {0x16497a4?, 0xc0018d7c68?}, {0xc0018d7c50?, 0xc000c7d810?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/cgo_unix.go:2[17](https://github.comxxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:18) +0x3b fp=0xc000c6efa8 sp=0xc000c6ef38 pc=0x6b4a1b
net.cgoLookupIP.func1()
	/opt/hostedtoolcache/go/1.[18](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:19).5/x64/src/net/cgo_unix.go:227 +0x36 fp=0xc000c6efe0 sp=0xc000c6efa8 pc=0x6b4e56
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000c6efe8 sp=0xc000c6efe0 pc=0x4658a1
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/cgo_unix.go:227 +0x12a

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc001018500, 0xc0021597c0, {{}, 0x0, {0xc0021323c0, 0x5}, {0xc0018d7c50, 0x12}, 0x0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0xc001018500, 0xc00162c500)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/roundtrip.go:17
github.com/k1LoW/go-github-client/v45/factory.roundTripper.RoundTrip({0xc001018500?, {0xc0012d090d?, 0x2d5a543a0?}}, 0xc00162c500)
	/home/runner/go/pkg/mod/github.com/k1!lo!w/go-github-client/v45@v45.2.3/factory/factory.go:[19](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:20)0 +0x147
net/http.send(0xc00162c100, {0x1d14f60, 0xc00210b7d0}, {0x160dc[20](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:21)?, 0x487201?, 0x2d0a420?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0020f8ae0, 0xc00162c100, {0x730000c00[21](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:22)3[23](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:24)c6?, 0x0?, 0x2d0a420?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0020f8ae0, 0xc00162c100)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:593
github.com/google/go-github/v45/github.(*Client).BareDo(0xc00009a500, {0x1d1e0c0, 0xc00012e000}, 0xc000c79d00)
	/home/runner/go/pkg/mod/github.com/google/go-github/v45@v45.2.0/github/github.go:643 +0x2bf
github.com/google/go-github/v45/github.(*Client).Do(0xc00009a500?, {0x1d1e0c0?, 0xc00012e000?}, 0xc002132380?, {0x135c2c0?, 0xc00210b830})
	/home/runner/go/pkg/mod/github.com/google/go-github/v45@v45.2.0/github/github.go:707 +0x79
github.com/google/go-github/v45/github.(*PullRequestsService).List(0xc00009a678, {0x1d1e0c0, 0xc00012e000}, {0xc00004a1f2?, 0x0?}, {0xc00004a1fb, 0x7}, 0xc0019fcc60?)
	/home/runner/go/pkg/mod/github.com/google/go-github/v45@v45.2.0/github/pulls.go:160 +0x158
github.com/k1LoW/octocov/gh.(*Gh).DetectCurrentPullRequestNumber(0xc001a0caa0, {0x1d1e0c0, 0xc00012e000}, {0xc00004a1f2, 0x8}, {0xc00004a1fb, 0x7})
	/home/runner/work/octocov/octocov/gh/gh.go:[24](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:25)7 +0x172
github.com/k1LoW/octocov/config.(*Config).CommentConfigReady(0xc001517b00)
	/home/runner/work/octocov/octocov/config/ready.go:77 +0xd4
github.com/k1LoW/octocov/cmd.glob..func7(0x2b11940?, {0x2d411f8?, 0x0?, 0x0?})
	/home/runner/work/octocov/octocov/cmd/root.go:332 +0xfd0
github.com/spf13/cobra.(*Command).execute(0x2b11940, {0xc0001021e0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x2b11940)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/k1LoW/octocov/cmd.Execute()
	/home/runner/work/octocov/octocov/cmd/root.go:500 +0xdb
main.main()
	/home/runner/work/octocov/octocov/main.go:48 +0x33

goroutine 4 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001a7c00)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 23 [select]:
github.com/lestrrat-go/backoff/v2.(*controller).loop(0xc0011c22a0)
	/home/runner/go/pkg/mod/github.com/lestrrat-go/backoff/v2@v2.0.8/controller.go:52 +0xbc
created by github.com/lestrrat-go/backoff/v2.newController
	/home/runner/go/pkg/mod/github.com/lestrrat-go/backoff/v2@v2.0.8/controller.go:46 +0x236

goroutine 9 [select]:
github.com/lestrrat-go/backoff/v2.(*controller).loop(0xc0019fc480)
	/home/runner/go/pkg/mod/github.com/lestrrat-go/backoff/v2@v2.0.8/controller.go:52 +0xbc
created by github.com/lestrrat-go/backoff/v2.newController
	/home/runner/go/pkg/mod/github.com/lestrrat-go/backoff/v2@v2.0.8/controller.go:46 +0x236

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f5ca5f1eb18, 0x72)
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc001750e00?, 0xc001820000?, 0x0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001750e00, {0xc001820000, 0xe58, 0xe58})
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_unix.go:167 +0x[25](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:26)a
net.(*netFD).Read(0xc001750e00, {0xc001820000?, 0xc0010366c0?, 0xc001820005?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000010080, {0xc001820000?, 0x58?, 0x7f5cd3d0a108?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000c72930, {0xc001820000?, 0x0?, 0x15c95a0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc0012f4cf8, {0x1d108e0, 0xc000c72930})
	/opt/hostedtoolcache/go/1.18.5/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0012f4a80, {0x1d13d80?, 0xc000010080}, 0x72?)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0012f4a80, 0x0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0012f4a80, {0xc001821000, 0x1000, 0x0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:1[28](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:29)5 +0x16f
net/http.(*persistConn).Read(0xc00110c7e0, {0xc001821000?, 0xc0015ff380?, 0xc00007bd30?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:19[29](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:30) +0x4e
bufio.(*Reader).fill(0xc0019fc240)
	/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc0019fc240, 0x1)
	/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc00110c7e0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1750 +0x173e

goroutine 8 [select]:
net/http.(*persistConn).writeLoop(0xc00110c7e0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1751 +0x1791

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x7f5ca5f1ea28, 0x72)
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/netpoll.go:[30](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:31)2 +0x89
internal/poll.(*pollDesc).wait(0xc001750f80?, 0xc001a90000?, 0x0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001750f80, {0xc001a90000, 0xe58, 0xe58})
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc001750f80, {0xc001a90000?, 0xc0017455e0?, 0xc001a90005?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000123a48, {0xc001a90000?, 0x58?, 0x7f5cd3d0a5b8?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0019c9ad0, {0xc001a90000?, 0x0?, 0x15c95a0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc0010c05f8, {0x1d108e0, 0xc0019c9ad0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0010c0380, {0x1d13d80?, 0xc000123a48}, 0x2?)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0010c0380, 0x0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0010c0380, {0xc001a91000, 0x1000, 0x0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:1285 +0x16f
net/http.(*persistConn).Read(0xc00110c900, {0xc001a91000?, 0x448680?, 0xc000076ec8?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc001a8d200)
	/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc001a8d200, 0x1)
	/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc00110c900)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1750 +0x173e

goroutine 37 [select]:
net/http.(*persistConn).writeLoop(0xc00110c900)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1751 +0x1791

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x7f5ca5f1e938, 0x72)
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000188a00?, 0xc001aca000?, 0x0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000188a00, {0xc001aca000, 0x4432, 0x4432})
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000188a00, {0xc001aca000?, 0xc001745860?, 0xc001acb34f?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000123a70, {0xc001aca000?, 0x7fffe3007fffe2?, 0x1fffdc007fffe4?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000c73350, {0xc001aca000?, 0x0?, 0x34?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc0010c1078, {0x1d108e0, 0xc000c73350})
	/opt/hostedtoolcache/go/1.18.5/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0010c0e00, {0x1d13d80?, 0xc000123a70}, 0x30f0?)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0010c0e00, 0x0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0010c0e00, {0xc001ab7000, 0x1000, 0x74c6e0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:1285 +0x16f
bufio.(*Reader).Read(0xc001ab4120, {0xc001a9e3c0, 0x9, 0x75aaa2?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x1d0f9a0, 0xc001ab4120}, {0xc001a9e3c0, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.18.5/x64/src/io/io.go:3[31](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:32) +0x9a
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.18.5/x64/src/io/io.go:350
net/http.http2readFrameHeader({0xc001a9e3c0?, 0x9?, 0xc0011fd920?}, {0x1d0f9a0?, 0xc001ab4120?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc001a9e380)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc0011dbf98)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc0011fe300)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:7439 +0xa65

goroutine 16 [select]:
net/http.setRequestCancel.func4()
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:398 +0x8b
created by net/http.setRequestCancel
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:397 +0x439

goroutine 50 [select]:
net.(*Resolver).lookupIPAddr(0x2d09220, {0x1d1e0f8?, 0xc0019fcfc0}, {0x16497a4, 0x3}, {0xc0018d7c50, 0xe})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/lookup.go:[32](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:33)5 +0x51b
net.(*Resolver).internetAddrList(0x1d1e0f8?, {0x1d1e0f8?, 0xc0019fcfc0?}, {0x16497a4, 0x3}, {0xc0018d7c50?, 0x12?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x2d411f8?, {0x1d1e0f8, 0xc0019fcfc0}, {0x164fbb1, 0x4}, {0x16497a4?, 0x0?}, {0xc0018d7c50, 0x12}, {0x0, ...})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc0019fcc00, {0x1d1e0c0, 0xc00012e000}, {0x16497a4, 0x3}, {0xc0018d7c50, 0x12})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/dial.go:406 +0x448
net.(*Dialer).Dial(0x7f5ca4ee2418?, {0x16497a4?, 0x5cd3d0a108?}, {0xc0018d7c50?, 0x118?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/dial.go:[35](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:36)1 +0x45
net/http.(*Transport).dial(0x0?, {0x1d1e0f8?, 0xc0019fcd20?}, {0x16497a4?, 0x2?}, {0xc0018d7c50?, 0x0?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1172 +0x5a
net/http.(*Transport).dialConn(0xc001018500, {0x1d1e0f8, 0xc0019fcd20}, {{}, 0x0, {0xc0021323c0, 0x5}, {0xc0018d7c50, 0x12}, 0x0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1607 +0x83f
net/http.(*Transport).dialConnFor(0xc0019899[40](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:41)?, 0xc000c7d810)
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1[41](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:42)8 +0x3d2

goroutine 51 [select]:
net.cgoLookupIP({0x1d1e088, 0xc002159800}, {0x16497a4, 0x3}, {0xc0018d7c50, 0xe})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/cgo_unix.go:228 +0x1aa
net.(*Resolver).lookupIP(0x2d09220, {0x1d1e088, 0xc002159800}, {0x16497a4, 0x3}, {0xc0018d7c50, 0xe})
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/lookup_unix.go:96 +0x128
net.glob..func1({0x1d1e088?, 0xc002159800?}, 0x0?, {0x16497a4?, 0x2d0a[42](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:43)0?}, {0xc0018d7c[50](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:51)?, 0x77[59](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:60)70?})
	/opt/hostedtoolcache/go/1.18.5/x[64](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:65)/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.18.5/x64/src/net/lookup.go:319 +0x9f
internal/singleflight.(*Group).doCall(0x2d09230, 0xc002104c30, {0xc0018d7c[68](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:69), 0x12}, 0xc000c7d[81](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:82)0?)
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.18.5/x64/src/internal/singleflight/singleflight.go:[88](https://github.com/xxxxxxxxxx/runs/8129049326?check_suite_focus=true#step:11:89) +0x2ec
```

## Other configs

test.yml
```yaml
...
      - name: Run tests
        shell: bash
        run: |
          go test --tags github_test ./pkg/... -coverprofile=coverage.out
      - name: Show coverage
        uses: k1LoW/octocov-action@v0

```

.octocov.yml
```yaml
coverage:
  if: true
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

```

**Comment by k1LoW** [comment]
@toshi0607 Oops!! I'll fix it soon.

**Comment by toshi0607** [comment]
It worked successfully again. Thank you for the prompt fix!!!

**Comment by k1LoW** [comment]
Oh good... And thanks for the report.
